config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :articles do
    resources :sections, except: [:show] do
      resources :revisions, only: [:index, :show]
    end
    resources :notes, except: [:show]
    resources :bibliographies, except: [:show]
    resources :revisions, only: [:index, :show]
  end
  resources :users, except: [:index, :edit, :update, :destroy]
  resources :sessions, except: [:index, :edit, :update, :destroy]
  resources :categories, only: [:new, :create]
  get '/users/:id/article_manager' => "users#article_manager", as: :article_manager
  # post '/users/:id/article_manager' => "users#post_article_manager"
  put '/articles/:article_id/categories/:category_id' => "articles#update_category"
  post '/sessions' => "sessions#create"
  delete '/sessions' => "sessions#destroy"
  get '/users/:user_id/admin_panel' => "users#admin_panel"
  post '/article/:id/publish' => "articles#update_publish"
  post '/article/:id/deny' => "articles#deny"
  post '/article/:id/request_submision' => "articles#request_submission"
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :article
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  include SessionsHelper
  
  def new
  	@article = Article.find(params[:article_id])
  	@note = Note.new
  end

  def create
    @article = Article.find(params[:article_id])
    note = Note.new(note_params)

    if note.comment? && article_owner
    	@article.notes << note
      	redirect_to @article, notice: 'Note was added.'
      else
      	redirect_to @article, notice:"You didn't add a note"
    end
  end

  def edit
  	@article = Article.find(params[:article_id])
  	@note = Note.find(params[:id])
    if !article_owner
    	redirect_to @article, notice:"You do not have permission to edit this article."
    end
  end

  def update
    note = Note.find(params[:id])
    note.assign_attributes(note_params)
    @article = Article.find(params[:article_id])
    if note.comment? && article_owner && note.save
      redirect_to @article, notice:"Note was updated!"
    else
      redirect_to edit_article_note_path, notice:"Note can't be blank!"
    end
  end

  def destroy
  	@article = Article.find(params[:article_id])
  	note = Note.find(params[:id])
  	note.destroy
  	redirect_to @article, notice: 'Note was deleted.'
  end

  private
    def note_params
  		params.require(:note).permit(:comment)
  	end

end

app/views/notes/_new_note.html.erb
<p>
	<%= f.label :note %>
    <%= f.text_field :comment, :size=>"100" %>
</p>

app/views/notes/_show.html.erb
<div id="note_<%=note.id%>">
	<li><%= note.comment %>
    <% if owner %>
		<p>
			<%= link_to 'Delete', article_note_path(@article.id, note.id), method: :delete, data: { confirm: 'Are you sure?' } %>
			<%= link_to 'Edit', edit_article_note_path(@article.id, note.id)%>
		</p>
	<% end %>
</div>

app/views/notes/edit.html.erb
<h1>Edit Note Form</h1>
<% if @article.errors.any? %>
    <%= render partial: 'errors/errors', locals: { errors: @article } %>
<% end %>

<%= form_for @note, url: article_note_path do |f| %>

<p>
	<%= f.label :notes %>
    <%= f.text_field :comment, :size=>"100" %>
</p>

<%= f.submit %>
<% end %>

app/views/notes/new.html.erb
<h3>Notes</h3>
<%= form_for :note, url: article_notes_path(@article.id) do |f| %>
  
  <% if @note.errors.any? %>
    <%= render partial: 'errors/errors', locals: { errors: @note } %>
  <% end %>
  <%= render partial: "notes/new_note", locals: {f: f}%>
   <p>
    <%= f.submit "Create Note" %>
  </p>

<% end %>