config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :articles do
    resources :sections, except: [:show] do
      resources :revisions, only: [:index, :show]
    end
    resources :notes, except: [:show]
    resources :bibliographies, except: [:show]
    resources :revisions, only: [:index, :show]
  end
  resources :users, except: [:index, :edit, :update, :destroy]
  resources :sessions, except: [:index, :edit, :update, :destroy]
  resources :categories, only: [:new, :create]
  get '/users/:id/article_manager' => "users#article_manager", as: :article_manager
  # post '/users/:id/article_manager' => "users#post_article_manager"
  put '/articles/:article_id/categories/:category_id' => "articles#update_category"
  post '/sessions' => "sessions#create"
  delete '/sessions' => "sessions#destroy"
  get '/users/:user_id/admin_panel' => "users#admin_panel"
  post '/article/:id/publish' => "articles#update_publish"
  post '/article/:id/deny' => "articles#deny"
  post '/article/:id/request_submision' => "articles#request_submission"
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :sections
  has_many :bibliographies
  has_many :revisions, as: :revisionable
  has_many :notes
  belongs_to :author, class_name: :User
  belongs_to :category
  # has_many :revisioned_sections, through: :sections, source: :revisions

  def self.all_published
    self.all.select { |article| article.find_newest_revision(true) != nil }
  end

  def newest_revision(search_for_published = true) # true = published; false = unpublished
    self.revisions.each do |revision|
      if revision.publication_status == search_for_published
        return revision
      end
    end
    return nil
  end

  def self.newest_published
    self.all.order(created_at: :desc).find {|article| article.newest_revision != nil}
  end

  def latest_update
    self.revisions.all.last
  end

  def self.alphabetical
    self.joins("JOIN revisions ON articles.id = revisions.revisionable_id AND revisions.publication_status = true").order('revisions.title')
  end

  def up_for_publication?
    published_id = self.newest_revision ? self.newest_revision.id : 0
    unpublished_id = self.newest_revision(false) ? self.newest_revision(false).id : 0
    p "************************************"
    p self
    p "published_id: #{published_id}"
    p "unpubulished_id: #{unpublished_id}"
    p "************************************"
    if published_id < unpublished_id
      return true
    end
    self.sections.each do |section|
      if section.up_for_publication?
        return true
      end
    end
    return false
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include SessionsHelper
  skip_before_filter  :verify_authenticity_token
  def index
    @articles = Article.alphabetical
    # @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new
    @article.author_id = current_user.id
    @article.submission_status = "unsubmitted"
    @revision = Revision.new(article_params)
    @article.category_id = params[:category_id]

    if @revision.title? && @revision.paragraph? && @article.save
    	@article.revisions << @revision
      redirect_to @article, notice: 'Article was successfully created.'
    else
      flash.clear
    	flash[:notice] = 'You need a title!' if !@revision.title?
    	flash[:alert] = 'You need a paragraph!' if !@revision.paragraph?
      render :new
    end
  end

  def edit
  	@article = Article.find(params[:id])
  	@revision = @article.revisions.last
    if !owner
       	flash[:no_access] = "You do not have permission to edit this article."
    	redirect_to @article
    end
  end

  def update
  	@article = Article.find(params[:id])
  	@revision = Revision.new(article_params)
  	if @revision.title? && @revision.paragraph?
  		@article.revisions << @revision
      redirect_to @article, notice: 'Article was updated.'
    else
      flash.clear
    	flash[:notice] = 'You need a title!' if !@revision.title?
    	flash[:alert] = 'You need a paragraph!' if !@revision.paragraph?
      redirect_to edit_article_path
    end
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy
    redirect_to articles_url, notice: 'Article was successfully deleted.'
  end

  def update_category
    article = Article.find(params[:article_id])
    article.update(category_id: params[:category_id])
    redirect_to article_path(article)
  end

  def update_publish
    @article = Article.find(params[:id])
    if @article.newest_revision == nil
      @article.newest_revision(false).update_attributes(:publication_status => true)
      @article.update_attributes(:submission_status => "unsubmitted")
      @article.save
      @article.sections.each do |section|
        if section.newest_revision
          section.newest_revision.update_attributes(:publication_status => false)
          section.newest_revision(false).update_attributes(:publication_status => true)
          section.save
        elsif section.newest_revision(false)
          section.newest_revision(false).update_attributes(:publication_status => true)
          section.save
        end
      end
    elsif @article.newest_revision(false).publication_status == false
      @article.newest_revision.update_attributes(:publication_status => false)
      @article.newest_revision(false).update_attributes(:publication_status => true)
      @article.update_attributes(:submission_status => "unsubmitted")
      @article.save
      @article.sections.each do |section|
        if section.newest_revision
          section.newest_revision.update_attributes(:publication_status => false)
          section.newest_revision(false).update_attributes(:publication_status => true)
          section.save
        elsif section.newest_revision(false)
          section.newest_revision(false).update_attributes(:publication_status => true)
          section.save
        end
      end

    end

    redirect_to "/users/#{current_user.id}/admin_panel"
  end

  def deny
    @article = Article.find(params[:id])
    @article.update_attributes(:submission_status => "needs sources")
    @article.save

    redirect_to "/users/#{current_user.id}/admin_panel"
  end

  def request_submission
    @article = Article.find(params[:id])
    @article.update_attributes(:submission_status => "submitted")
    @article.save

    redirect_to "/users/#{current_user.id}/article_manager?filter_by=unpublished"
  end

  private
  	def article_params
    	params.require(:revision).permit(:title, :paragraph)
  	end

  	def bib_params
  		params.require(:revision).permit(:reference, :resource_type)
  	end
  	def note_params
  		params.require(:revision).permit(:comment)
  	end

end

app/helpers/article_helper.rb
module ArticleHelper
end

app/views/articles/edit.html.erb
<h1>Edit Article Form</h1>
<% if @article.errors.any? %>
    <%= render partial: 'errors/errors', locals: { errors: @article } %>
<% end %>

<%= form_for @revision, url: article_path do |f| %>

<p>
	<%= f.label :title %>
	<%= f.text_field :title %>
</p>

<p>
<div>
	<%= f.cktext_area :paragraph, rows: 10 %>
<div>	
</p>
<%= f.submit %>
<% end %>

app/views/articles/index.html.erb
<div>
  <h1>All articles:</h1>
  <ul>
  <% @articles.each do |article| %>
    <li><%= link_to article.newest_revision.title, article %></li>
  <% end %>
  </ul>
</div>

app/views/articles/new.html.erb
<h1>New Article Form</h1>
<%= form_for :revision, url: articles_path(@article) do |f| %>

  <% if @article.errors.any? %>
    <%= render partial: 'errors/errors', locals: { errors: @article } %>
  <% end %>

  <p>
    <%= f.label :title %>
    <%= f.text_field :title, :size=>"50" %>
  </p>
  <p>
    <%= f.label :image_url %>
    <%= f.text_field :image_url, :size=>"50" %>
  </p>
  <div>
    <%= f.cktext_area :paragraph, rows: 10 %>
  </div>
  <h3>Category</h3>
  <select name="category_id">
    <% Category.all.each do |category| %>
      <option value=<%= category.id %>><%= category.name %></option>
    <% end %>
  </select>
  <p>
    <%= f.submit "Create Article" %>
  </p>

<% end %>

app/views/articles/show.html.erb
<% if owner %>
	<h1><%= @article.latest_update.title %></h1>
  <span>category: <%= @article.category.name %></span>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Change Category<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <% Category.all.each do |category| %>
            <li><%= link_to category.name, "/articles/#{@article.id}/categories/#{category.id}", method: :put %></li>
          <% end %>
          <li role="separator" class="divider"></li>
          <li><%= link_to "Create New Category", new_category_path %></a></li>
        </ul>
      </li>
    </div>
	<p><%= @article.latest_update.paragraph.html_safe %></p>
	<p>
	<%= link_to 'Destroy', @article, method: :delete, data: { confirm: 'Are you sure?' } %>
	<%= link_to 'Edit', edit_article_path(@article)%>
	</p>
<% else  %>
	<h1><%= @article.newest_revision.title %></h1>
	<p><%= "<img src='#{@article.newest_revision.image_url}'>".html_safe %></p>
	<p><%= @article.newest_revision.paragraph.html_safe %></p>
<% end %>

<hr>
<h2>Sections</h2>
<%= link_to 'New', new_article_section_path(@article.id) if owner%>
<% @article.sections.each do |section| %>
	<% if section.revisions.exists? %>
		<%= render partial: 'sections/show', locals: { section: section } %>
    <% end %>
<% end %>
<hr>
<h2>Notes</h2>
<%= link_to 'New', new_article_note_path(@article.id) if owner%>
<ol>
  <% @article.notes.each do |note| %>
    <%= render partial: 'notes/show', locals: { note: note } %>
  <% end %>
</ol>
<hr>
<h2>References</h2>
<%= link_to 'New', new_article_bibliography_path(@article.id) if owner%>
<ul>
  <% @article.bibliographies.each do |bib| %>
    <%= render partial: 'bibliographies/show', locals: { bib: bib } %>
  <% end %>
</ul>