config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :articles do
    resources :sections, except: [:show] do
      resources :revisions, only: [:index, :show]
    end
    resources :notes, except: [:show]
    resources :bibliographies, except: [:show]
    resources :revisions, only: [:index, :show]
  end
  resources :users, except: [:index, :edit, :update, :destroy]
  resources :sessions, except: [:index, :edit, :update, :destroy]
  resources :categories, only: [:new, :create]
  get '/users/:id/article_manager' => "users#article_manager", as: :article_manager
  # post '/users/:id/article_manager' => "users#post_article_manager"
  put '/articles/:article_id/categories/:category_id' => "articles#update_category"
  post '/sessions' => "sessions#create"
  delete '/sessions' => "sessions#destroy"
  get '/users/:user_id/admin_panel' => "users#admin_panel"
  post '/article/:id/publish' => "articles#update_publish"
  post '/article/:id/deny' => "articles#deny"
  post '/article/:id/request_submision' => "articles#request_submission"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :articles, foreign_key: :author_id

  validates :username, {uniqueness: true, presence: true, case_sensitive: false}
  validates :password, length: { minimum: 8 }

  validate :password_must_contain_number

  def password_must_contain_number
    unless !!(password =~ /\d/)
      errors.add(:password, "must contain at least one number")
    end
  end

  def published_articles
    self.articles.select{|article| ( (!article.up_for_publication?) && (article.submission_status == "unsubmitted") ) }
  end

  def unpublished_articles
    self.articles.select{|article| ((article.up_for_publication?) && (article.submission_status == "unsubmitted") )}
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper
  skip_before_filter  :verify_authenticity_token
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_deets)
    if @user.save
      login_user
      redirect_to(root_path)
    else
      render action: 'new'
    end
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def edit
  end

  def update
  end

  def admin_panel
    @current_search = "Unpublished"
    @unpublished = Article.where("submission_status = 'submitted'")
  end

  def article_manager
    p "****************"
    p "FILTER"
    p params[:filter_by]
    if current_user.id == params[:id].to_i
      @user = current_user
      case params[:filter_by]
      when nil
        @title = "Your articles"
        @articles = @user.articles
      when "published"
        @title = "Your published articles"
        @articles = @user.published_articles
      when "unpublished"
        @title = "Your unpublished articles"
        @articles = @user.unpublished_articles
      end

    else
      redirect_to(root_path)
    end
  end

private
  def user_deets
      params.require(:user).permit(:username, :password)
  end
end

app/helpers/user_helper.rb
module UserHelper
  def title_string
    if @user.admin == true
      "Admin"
    else
      "Member"
    end
  end

  def is_admin
    if logged_in
      current_user.admin
    else
      false
    end
  end
end

app/views/users/admin_panel.html.erb
<% if is_admin %>
<div class="container">
  <div class="row">
    <div class="col-md-10"></div>
    <div class="col-md-2">
      <!-- <div class="dropdown">
          <button id="dLabel" class="btn btn-default" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= @current_search %>
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" aria-labelledby="dLabel" id="dropdown-lang">
            <li><a href="/users/<%= current_user.id %>/admin_panel/unpublished">Unpublished</a></li>
            <li><a href="/users/<%= current_user.id %>/admin_panel/sources">Need sources</a></li>
          </ul>
        </div> -->
    </div>
  </div>

  <div class="row">&nbsp;</div>
  <div class="row">&nbsp;</div>


  <div class="row">
    <div class="col-md-2"></div>

    <div class="col-md-10">
      <% @unpublished.each do |article| %>
      <div class="row">
        <span class="article-title"><a href="/articles/<%= article.id %>"><%= article.newest_revision(false).title %></a></span>
        <span class="article-author">submitted by: <%= article.author.username %>
      </div>
      <form class="admin-panel-buttons" action="/article/<%= article.id %>/publish" method="post">
        <button type = "submit" class = "btn btn-default btn-xs">
          Publish
        </button>
      </form>
      <form class="admin-panel-buttons" action="/article/<%= article.id %>/deny" method="post">
        <button type = "submit" class = "btn btn-default btn-xs">
          Send Back
        </button>
      </form>
      <div class="row">&nbsp;</div>
      <div class="row">&nbsp;</div>

      <% end %>

    </div>
  </div>
</div>
<% else %>
<center><h1>Error: You need admin privledges to access this page</h1></center>
<% end %>

app/views/users/article_manager.html.erb
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Filter by: <span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li><%= link_to "none", article_manager_path(filter_by: nil) %></li>
      <li><%= link_to "published", article_manager_path(filter_by: "published") %></li>
      <li><%= link_to "unpublished", article_manager_path(filter_by: "unpublished") %></li>
      <li><%= link_to "pending", article_manager_path(filter_by: "pending") %></li>
    </ul>
  </li>
</div>
<div>
  <h1><%= @title %>:</h1>
  <ul>
  <% @articles.each do |article| %>
    <% if article.newest_revision  %>
      <li><%= link_to article.newest_revision.title, article %></li>
    <% else %>
      <li><%= link_to article.newest_revision(false).title, article %></li>
    <% end %>
    <% if params[:filter_by] == "unpublished" %>
      <%= link_to "submit for review", "/article/#{article.id}/request_submision", method: :post %>
    <% end %>
  <% end %>
  </ul>
</div>
<%= button_to "Create New Article", new_article_path, method: :get %>

app/views/users/new.html.erb
<div class="wrapper">
  <form class="form-signin" action="/users" method="post">
    <% if @user.errors.any? %>
      <% @user.errors.full_messages.each do |error| %>
        <p style="color: red"><%= error %>!</p>
      <% end %>
    <% end %>
    <h2 class="form-signin-heading">Please Register</h2>
    <input type="text" class="form-control" name="user[username]" placeholder="Username" required="" autofocus="" />
    <input type="password" class="form-control" name="user[password]" placeholder="Password" required=""/>
  </br>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>
  </form>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <% if @user %>
      <span class="profile-username"><%= @user.username %></span> <span class="profile-title"><%= title_string %></span>
      <% else %>
      <center><h1>Error: Account not found</h1></center>
      <% end %>
    </div>
  </div>
</div>