config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :articles do
    resources :sections, except: [:show] do
      resources :revisions, only: [:index, :show]
    end
    resources :notes, except: [:show]
    resources :bibliographies, except: [:show]
    resources :revisions, only: [:index, :show]
  end
  resources :users, except: [:index, :edit, :update, :destroy]
  resources :sessions, except: [:index, :edit, :update, :destroy]
  resources :categories, only: [:new, :create]
  get '/users/:id/article_manager' => "users#article_manager", as: :article_manager
  # post '/users/:id/article_manager' => "users#post_article_manager"
  put '/articles/:article_id/categories/:category_id' => "articles#update_category"
  post '/sessions' => "sessions#create"
  delete '/sessions' => "sessions#destroy"
  get '/users/:user_id/admin_panel' => "users#admin_panel"
  post '/article/:id/publish' => "articles#update_publish"
  post '/article/:id/deny' => "articles#deny"
  post '/article/:id/request_submision' => "articles#request_submission"
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :article
  has_many :revisions, as: :revisionable

  def newest_revision(search_for_published = true) # true = published; false = unpublished
    self.revisions.each do |revision|
      if revision.publication_status == search_for_published
        return revision
      end
    end
    return nil
  end

  def latest_update
    self.revisions.all.last
  end

  def up_for_publication?
    published_id = self.newest_revision ? self.newest_revision.id : 0
    unpublished_id = self.newest_revision(false) ? self.newest_revision(false).id : 0
    p "************************************"
    p self
    p "published_id: #{published_id}"
    p "unpubulished_id: #{unpublished_id}"
    p "************************************"
    if published_id < unpublished_id
      return true
    end
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  include SessionsHelper
  
  def new
  	@article = Article.find(params[:article_id])
  	@section = Section.new
  end

  def create
    @article = Article.find(params[:article_id])
    @section = Section.new
    @revision = Revision.new(section_params)

    if @revision.title? && @revision.paragraph? && article_owner
    	 @article.sections << @section
       @section.revisions << @revision
       redirect_to @article, notice: 'Section was added.'
    else
       flash.clear
       flash[:notice] = 'You need a title!' if !@revision.title?
       flash[:alert] = 'You need a paragraph!' if !@revision.paragraph?
       render :new
    end
  end

  def edit
  	@article = Article.find(params[:article_id])
  	@section = Section.find(params[:id])
    @revision = @section.revisions.last
    if !article_owner
    	redirect_to @article, notice:"You do not have permission to edit this article."
    end
  end

  def update
    @article = Article.find(params[:article_id])
    section = Section.find(params[:id])
    @revision = Revision.new(section_params)

    if @revision.title? && @revision.paragraph? && article_owner
       section.revisions << @revision
       redirect_to @article, notice:"Section was updated!"
    else
       flash.discard[:notice] = 'You need a title!' if !@revision.title?
       flash.discard[:alert] = 'You need a paragraph!' if !@revision.paragraph?
       render :new, notice:"You didn't add a section"
    end
  end

  def destroy
  	@article = Article.find(params[:article_id])
  	section = Section.find(params[:id])
  	section.destroy
  	redirect_to @article, notice: 'Section was deleted.'
  end

  private
    def section_params
  		params.require(:revision).permit(:title, :paragraph)
  	end

end

app/views/sections/_show.html.erb
<div id="section_<%=section.id%>">
	<% if section.revisions.exists? %>
		<% if owner %>
			<h3><%= section.latest_update.title %></h3>
			<p><%= section.latest_update.paragraph.html_safe %></p>
			<p>
				<%= link_to 'Delete', article_section_path(@article.id, section.id), method: :delete, data: { confirm: 'Are you sure?' } %>
				<%= link_to 'Edit', edit_article_section_path(@article.id, section.id)%>
			</p>
		<% else  %>
			<% if section.newest_revision != nil %>
				<h3><%= section.newest_revision.title %></h3>
				<p><%= section.newest_revision.paragraph.html_safe %></p>
			<% end %>
		<% end %>
	<% end %>
</div>

app/views/sections/edit.html.erb
<h1>Edit Section Form</h1>
<% if @article.errors.any? %>
    <%= render partial: 'errors/errors', locals: { errors: @article } %>
<% end %>

<%= form_for @revision, url: article_section_path do |f| %>

<p>
	<%= f.label :title %>
	<%= f.text_field :title %>
</p>

<p>
<div>
	<%= f.cktext_area :paragraph, rows: 10 %>
<div>	
</p>
<%= f.submit %>
<% end %>

app/views/sections/new.html.erb
<h1>New Section</h1>

<%= form_for :revision, url: article_sections_path(@article.id) do |f| %>
  
  <% if @article.errors.any? %>
    <%= render partial: 'errors/errors', locals: { errors: @article } %>
  <% end %>

  <p>
    <%= f.label :title %>
    <%= f.text_field :title, :size=>"50" %>
  </p>
  <div>
    <%= f.cktext_area :paragraph, rows: 10 %>
  </div>
  
  <p>
    <%= f.submit "Create Section" %>
  </p>

<% end %>